"""Optional extra catalog weights. Registered from gitignored private/ at runtime."""


def register(add) -> None:
    add(
        "lora.clothes_remover_kontext",
        filename="clothes_remover_v0.safetensors",
        role="lora",
        status="missing",
        download_source="https://huggingface.co/wkrisdiyanto/fluxkontextdevlora",
    )
    add(
        "lora.content_unlock_flux",
        filename="aidmaNSFWunlock-FLUX-V0.2.safetensors",
        role="lora",
        status="missing",
        download_source="https://huggingface.co/shahtab/FLUXNSFWunlock",
    )
    add(
        "lora.cof_flux",
        filename="flux_facial_fluid_v1.safetensors",
        role="lora",
        status="missing",
        download_source="https://civitai.com/models/858262",
    )
    add(
        "lora.bust_enhance_flux",
        filename="flux_kontext_figure_reshape_v1.safetensors",
        role="lora",
        status="missing",
        download_source="https://civitai.com/models/1802814/bigger-breasts-and-butts-flux-kontext-lora",
    )
    add(
        "lora.hip_enhance_flux",
        filename="flux_kontext_figure_reshape_v1.safetensors",
        role="lora",
        status="missing",
        download_source="https://civitai.com/models/1802814/bigger-breasts-and-butts-flux-kontext-lora",
    )
    add(
        "lora.video_lightx2v_unc_high",
        filename="Wan2.2_LightX2V_high_n54vv.safetensors",
        role="lora",
        status="missing",
        download_source="https://huggingface.co/rzgar/Wan2.2_LightX2V_4Step_Uncensored",
    )
    add(
        "lora.video_lightx2v_unc_low",
        filename="Wan2.2_LightX2V_low_n54vv.safetensors",
        role="lora",
        status="missing",
        download_source="https://huggingface.co/rzgar/Wan2.2_LightX2V_4Step_Uncensored",
    )
    add(
        "lora.video_male_gen_high",
        filename="male_genitalia_enhancer_high.safetensors",
        role="lora",
        status="missing",
    )
    add(
        "lora.video_male_gen_low",
        filename="male_genitalia_enhancer_low.safetensors",
        role="lora",
        status="missing",
    )
    add(
        "lora.video_female_gen_high",
        filename="female_genitalia_enhancer_high.safetensors",
        role="lora",
        status="missing",
    )
    add(
        "lora.video_female_gen_low",
        filename="female_genitalia_enhancer_low.safetensors",
        role="lora",
        status="missing",
    )
    add(
        "lora.video_anatomy_m_high",
        filename="PENISLORA_22_i2v_HIGH_e320.safetensors",
        role="lora",
        status="missing",
        download_source="https://huggingface.co/liangwc25/wan-penislora-22-i2v",
    )
    add(
        "lora.video_deep_a_high",
        filename="Wan2.2_I2V_Blink_Blowjob_HIGH.safetensors",
        role="lora",
        status="missing",
        download_source="https://huggingface.co/UnifiedHorusRA/TheWan2.2I2V3",
    )
    add(
        "lora.video_deep_a_low",
        filename="Wan2.2_I2V_Blink_Blowjob_LOW.safetensors",
        role="lora",
        status="missing",
        download_source="https://huggingface.co/UnifiedHorusRA/TheWan2.2I2V3",
    )
    add(
        "lora.video_dr34ml4y_high",
        filename="DR34ML4Y_I2V_14B_HIGH_V2.safetensors",
        role="lora",
        status="missing",
        download_source="https://huggingface.co/lopi999/Wan2.2-DR34ML4Y-AIO_NSFW-LoRA",
    )
    add(
        "lora.video_dr34ml4y_low",
        filename="DR34ML4Y_I2V_14B_LOW_V2.safetensors",
        role="lora",
        status="missing",
        download_source="https://huggingface.co/lopi999/Wan2.2-DR34ML4Y-AIO_NSFW-LoRA",
    )
    add(
        "lora.video_finish_high",
        filename="Wan2.2_I2V_Cumshot_HIGH.safetensors",
        role="lora",
        status="missing",
        download_source="https://huggingface.co/onamissiononamission/F4C3SPL4SH-Cumshot-I2V-Wan2.2-Video-LoRa-K3NK",
    )
    add(
        "lora.video_finish_low",
        filename="Cumshot_LoRA.safetensors",
        role="lora",
        status="missing",
        download_source="https://huggingface.co/onamissiononamission/F4C3SPL4SH-Cumshot-I2V-Wan2.2-Video-LoRa-K3NK",
    )
    add(
        "lora.video_cumshot_high",
        filename="Wan2.2_I2V_Cumshot_HIGH.safetensors",
        role="lora",
        status="missing",
        download_source="https://huggingface.co/onamissiononamission/F4C3SPL4SH-Cumshot-I2V-Wan2.2-Video-LoRa-K3NK",
    )
    add(
        "lora.video_cumshot_low",
        filename="Cumshot_LoRA.safetensors",
        role="lora",
        status="missing",
        download_source="https://huggingface.co/onamissiononamission/F4C3SPL4SH-Cumshot-I2V-Wan2.2-Video-LoRa-K3NK",
    )
    add(
        "lora.video_missionary_high",
        filename="Wan2.2_I2V_Missionary_HIGH.safetensors",
        role="lora",
        status="missing",
        download_source="https://huggingface.co/profpeng/wanmissionsex",
    )
    add(
        "lora.video_missionary_low",
        filename="Wan2.2_I2V_Missionary_LOW.safetensors",
        role="lora",
        status="missing",
        download_source="https://huggingface.co/profpeng/wanmissionsex",
    )
    add(
        "lora.video_cowgirl_high",
        filename="Wan2.2_I2V_Cowgirl_HIGH.safetensors",
        role="lora",
        status="missing",
        download_source="https://huggingface.co/KeyOpening8063587/AssertiveCowgirl",
    )
    add(
        "lora.video_cowgirl_low",
        filename="Wan2.2_I2V_Cowgirl_LOW.safetensors",
        role="lora",
        status="missing",
        download_source="https://huggingface.co/KeyOpening8063587/AssertiveCowgirl",
    )
    add(
        "lora.video_doggy_high",
        filename="Wan2.2_I2V_Doggy_HIGH.safetensors",
        role="lora",
        status="missing",
        download_source="https://huggingface.co/mega281/lora",
    )
    add(
        "lora.video_doggy_low",
        filename="Wan2.2_I2V_Doggy_LOW.safetensors",
        role="lora",
        status="missing",
        download_source="https://huggingface.co/mega281/lora",
    )
    add(
        "lora.video_handjob_high",
        filename="Wan2.2_I2V_Handjob_HIGH.safetensors",
        role="lora",
        status="missing",
        download_source="https://huggingface.co/Melonhead123/WAN2.2-I2V-Handjob-One-Two-handed",
    )
    add(
        "lora.video_handjob_low",
        filename="Wan2.2_I2V_Handjob_LOW.safetensors",
        role="lora",
        status="missing",
        download_source="https://huggingface.co/Melonhead123/WAN2.2-I2V-Handjob-One-Two-handed",
    )
    # Misc / staged-for-removal (models/loras/miscellaneous/) — still wired for remote text use.
    add(
        "lora.video_oral_insertion_high",
        filename="miscellaneous/Wan2.2_I2V_Oral_Insertion_HIGH.safetensors",
        role="lora",
        status="missing",
    )
    add(
        "lora.video_oral_insertion_low",
        filename="miscellaneous/Wan2.2_I2V_Oral_Insertion_LOW.safetensors",
        role="lora",
        status="missing",
    )
    add(
        "lora.video_reveal_penis_high",
        filename="miscellaneous/Wan2.2_I2V_Reveal_Penis_HIGH.safetensors",
        role="lora",
        status="missing",
    )
    add(
        "lora.video_reveal_penis_low",
        filename="miscellaneous/Wan2.2_I2V_Reveal_Penis_LOW.safetensors",
        role="lora",
        status="missing",
    )
    add(
        "lora.cof_misc_cuminator",
        filename="miscellaneous/flux_cum_on_face_cuminator.safetensors",
        role="lora",
        status="missing",
    )
    add(
        "lora.cof_misc_cumhere",
        filename="miscellaneous/flux_cumhere_v1.safetensors",
        role="lora",
        status="missing",
    )
    add(
        "lora.cof_misc_massive",
        filename="miscellaneous/flux_facial_cum_massive.safetensors",
        role="lora",
        status="missing",
    )
    add(
        "lora.cof_misc_char_friendly",
        filename="miscellaneous/flux_char_friendly_facial.safetensors",
        role="lora",
        status="missing",
    )
    add(
        "lora.cof_misc_naf",
        filename="miscellaneous/flux_not_another_facial.safetensors",
        role="lora",
        status="missing",
    )
