"""Optional extra catalog weights. Registered from gitignored private/ at runtime."""


def register(add) -> None:
    add(
        "lora.clothes_remover_kontext",
        filename="clothes_remover_v0.safetensors",
        role="lora",
        status="missing",
        download_source="https://huggingface.co/wkrisdiyanto/fluxkontextdevlora",
    )
    add(
        "lora.content_unlock_flux",
        filename="aidmaNSFWunlock-FLUX-V0.2.safetensors",
        role="lora",
        status="missing",
        download_source="https://huggingface.co/shahtab/FLUXNSFWunlock",
    )
    add(
        "lora.cof_flux",
        filename="COF_v6.safetensors",
        role="lora",
        status="missing",
        download_source="https://civitai.com/models/725999",
    )
    add(
        "lora.see_through_flux",
        filename="See_through_clothes_FLUX.safetensors",
        role="lora",
        status="missing",
        download_source="https://civitai.com/models/1028424",
    )
    add(
        "lora.wet_shirt_flux",
        filename="Wet_ClothesHair_FLUX.safetensors",
        role="lora",
        status="missing",
        download_source="https://civitai.com/models/1459149/wet-clotheshair-flux",
    )
    add(
        "lora.bust_enhance_flux",
        filename="flux_kontext_figure_reshape_v1.safetensors",
        role="lora",
        status="missing",
        download_source="https://civitai.com/models/1802814/bigger-breasts-and-butts-flux-kontext-lora",
    )
    add(
        "lora.hip_enhance_flux",
        filename="flux_kontext_figure_reshape_v1.safetensors",
        role="lora",
        status="missing",
        download_source="https://civitai.com/models/1802814/bigger-breasts-and-butts-flux-kontext-lora",
    )
    add(
        "lora.video_lightx2v_unc_high",
        filename="Wan2.2_LightX2V_high_n54vv.safetensors",
        role="lora",
        status="missing",
        download_source="https://huggingface.co/rzgar/Wan2.2_LightX2V_4Step_Uncensored",
    )
    add(
        "lora.video_lightx2v_unc_low",
        filename="Wan2.2_LightX2V_low_n54vv.safetensors",
        role="lora",
        status="missing",
        download_source="https://huggingface.co/rzgar/Wan2.2_LightX2V_4Step_Uncensored",
    )
    add(
        "lora.video_male_gen_high",
        filename="male_genitalia_enhancer_high.safetensors",
        role="lora",
        status="missing",
    )
    add(
        "lora.video_male_gen_low",
        filename="male_genitalia_enhancer_low.safetensors",
        role="lora",
        status="missing",
    )
    add(
        "lora.video_female_gen_high",
        filename="female_genitalia_enhancer_high.safetensors",
        role="lora",
        status="missing",
    )
    add(
        "lora.video_female_gen_low",
        filename="female_genitalia_enhancer_low.safetensors",
        role="lora",
        status="missing",
    )
    add(
        "lora.video_anatomy_m_high",
        filename="PENISLORA_22_i2v_HIGH_e320.safetensors",
        role="lora",
        status="missing",
        download_source="https://huggingface.co/liangwc25/wan-penislora-22-i2v",
    )
    add(
        "lora.video_deep_a_high",
        filename="Wan2.2_I2V_Deepthroat_Blowjob_High.safetensors",
        role="lora",
        status="missing",
        download_source="https://huggingface.co/Daxxx3D/Deepthroat_Blowjob_Wan2.2_I2V",
    )
    add(
        "lora.video_deep_a_low",
        filename="Wan2.2_I2V_Deepthroat_Blowjob_Low.safetensors",
        role="lora",
        status="missing",
        download_source="https://huggingface.co/Daxxx3D/Deepthroat_Blowjob_Wan2.2_I2V",
    )
    add(
        "lora.video_dr34ml4y_high",
        filename="DR34ML4Y_I2V_14B_HIGH.safetensors",
        role="lora",
        status="missing",
        download_source="https://huggingface.co/lopi999/Wan2.2-DR34ML4Y-AIO_NSFW-LoRA",
    )
    add(
        "lora.video_dr34ml4y_low",
        filename="DR34ML4Y_I2V_14B_LOW.safetensors",
        role="lora",
        status="missing",
        download_source="https://huggingface.co/lopi999/Wan2.2-DR34ML4Y-AIO_NSFW-LoRA",
    )
    add(
        "lora.video_finish_low",
        filename="Cumshot_LoRA.safetensors",
        role="lora",
        status="missing",
        download_source="https://huggingface.co/onamissiononamission/F4C3SPL4SH-Cumshot-I2V-Wan2.2-Video-LoRa-K3NK",
    )
    add(
        "lora.video_coachbate_low",
        filename="CoachBate_PENIS_LoRA.safetensors",
        role="lora",
        status="missing",
    )
    add(
        "lora.video_smoothmix_low",
        filename="SmoothMix_Males.safetensors",
        role="lora",
        status="missing",
    )
    add(
        "lora.oral_pov_flux",
        filename="flux_pov_a_v1.safetensors",
        role="lora",
        status="missing",
        download_source="https://civitai.com/models/678730",
    )
    add(
        "lora.male_anatomy_flux",
        filename="flux_anatomy_m_v1.safetensors",
        role="lora",
        status="missing",
        download_source="https://civitai.com/models/824972",
    )
    add(
        "lora.detailed_hands_flux",
        filename="flux_hands_detail_v1.safetensors",
        role="lora",
        status="missing",
        download_source="https://civitai.com/models/891074",
    )
